name: Visual Regression

on: [push]

jobs:
  cypress:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '15.x'
      - run: npm ci
        working-directory: ./cypress
      - run: npm test
        working-directory: ./cypress

  playwright:

    runs-on: ubuntu-latest
    container: mcr.microsoft.com/playwright:focal

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '15.x'
      - run: npm ci
        working-directory: ./playwright
      - run: npx playwright install
        working-directory: ./playwright
      - run: npm test
        working-directory: ./playwright